# Generated by Django 3.2 on 2021-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
