# Generated by Django 3.2 on 2021-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210829_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(),
        ),
    ]
